---
kind: pipeline
name: docs

steps:
  - name: build
    image: python:3-bullseye
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DEPLOY_KEY:
        from_secret: GITHUB_DEPLOY_KEY
    commands:
      - |-
        if [ -n "$SSH_PROXY" ]; then
          if [ -n "$DEBIAN_MIRROR" ]; then
            sed -i "s@http://.\+\.debian\.org/debian@$${DEBIAN_MIRROR}@g" /etc/apt/sources.list
          fi
          apt-get update
          apt-get -y install connect-proxy
          mkdir -p ~/.ssh/
          echo "ProxyCommand connect -H $SSH_PROXY %h %p" > ~/.ssh/config
        fi
      - export DEPLOY_KEY
      - bash ./scripts/ci-build-docs.sh
---
kind: pipeline
name: notification

clone:
  disable: true
steps:
  - name: youdu
    image: registry.wlf.com/drone-youdu
    failure: ignore
    settings:
      url:
        from_secret: YOUDU_URL
      buin:
        from_secret: YOUDU_BUIN
      app_id:
        from_secret: YOUDU_APP_ID
      aes_key:
        from_secret: YOUDU_AES_KEY
      from:
        from_secret: YOUDU_FROM
      to:
        from_secret: YOUDU_TO
depends_on:
  - docs
trigger:
  status:
    - success
    - failure
