# -*- coding=UTF-8 -*-
# Code generated by scripts\python-version-updater.js, DO NOT EDIT
"""
version info.
"""

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from datetime import datetime

VERSION = '2023.1.0'
RELEASE_DATE = datetime.fromtimestamp(1689575638)
LAST_GIT_COMMIT_DESCRIBE = 'v2023.0.0-46-g75233e1'
LAST_GIT_COMMIT_HASH = '75233e166109c5ffd8054a3ff573e1dee7f081d8'
LAST_GIT_COMMIT_AUTHOR_NAME = 'NateScarlet'
LAST_GIT_COMMIT_AUTHOR_EMAIL = 'NateScarlet@Gmail.com'
LAST_GIT_COMMIT_AUTHOR_DATE = datetime.fromtimestamp(1689315644)
LAST_GIT_COMMIT_SUBJECT = 'chore(nuke): Hatch: update ui'
LAST_GIT_COMMIT_BODY = ''
