# -*- coding=UTF-8 -*-
# Code generated by scripts\python-version-updater.js, DO NOT EDIT
"""
version info.
"""

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from datetime import datetime

VERSION = '2025.0.0'
RELEASE_DATE = datetime.fromtimestamp(1735789429)
LAST_GIT_COMMIT_DESCRIBE = 'v2024.1.0-18-g6a78e2c5'
LAST_GIT_COMMIT_HASH = '6a78e2c5420ecad154c9d842186937803400e9bd'
LAST_GIT_COMMIT_AUTHOR_NAME = 'NateScarlet'
LAST_GIT_COMMIT_AUTHOR_EMAIL = 'NateScarlet@Gmail.com'
LAST_GIT_COMMIT_AUTHOR_DATE = datetime.fromtimestamp(1735789410)
LAST_GIT_COMMIT_SUBJECT = 'chore: update .versionrc.js'
LAST_GIT_COMMIT_BODY = ''
