# -*- coding=UTF-8 -*-
# Code generated by scripts\python-version-updater.js, DO NOT EDIT
"""
version info.
"""

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from datetime import datetime

VERSION = '2022.2.2'
RELEASE_DATE = datetime.fromtimestamp(1655883466)
LAST_GIT_COMMIT_DESCRIBE = 'v2022.2.1-3-ge7df8e3'
LAST_GIT_COMMIT_HASH = 'e7df8e3684ba0051bdc9c5665197e522cd693057'
LAST_GIT_COMMIT_AUTHOR_NAME = 'NateScarlet'
LAST_GIT_COMMIT_AUTHOR_EMAIL = 'NateScarlet@Gmail.com'
LAST_GIT_COMMIT_AUTHOR_DATE = datetime.fromtimestamp(1655883308)
LAST_GIT_COMMIT_SUBJECT = 'fix(deps): missing vendor dependencies'
LAST_GIT_COMMIT_BODY = ''
