# -*- coding=UTF-8 -*-
"""
license check. only intend to block non-programer user.
DO NOT change this file without permission.
"""

from __future__ import absolute_import, division, print_function, unicode_literals

import base64

eval(
    compile(
        base64.b64decode(
            "IyAtKi0gY29kaW5nPVVURi04IC0qLQojIHB5cmlnaHQ6IHN0cmljdCwgcmVwb3J0VHlwZUNvbW1lbnRVc2FnZT1ub25lCgpmcm9tIF9fZnV0dXJlX18gaW1wb3J0IGFic29sdXRlX2ltcG9ydCwgZGl2aXNpb24sIHByaW50X2Z1bmN0aW9uLCB1bmljb2RlX2xpdGVyYWxzCgppbXBvcnQgZGF0ZXRpbWUgYXMgZHQKaW1wb3J0IG9zCmltcG9ydCBzb2NrZXQKCmZyb20gLiBpbXBvcnQgX192ZXJzaW9uX18KCmltcG9ydCB3dWxpZmFuZwoKY2xhc3MgTGljZW5zZUVycm9yKFJ1bnRpbWVFcnJvcik6CiAgICBwYXNzCgoKZGVmIGNoZWNrKCk6CiAgICBleHBpcmVfYXQgPSBkdC5kYXRlKDIwMjYsIDYsIDEpCgogICAgdHJ5OgogICAgICAgIGlmICgKICAgICAgICAgICAgc29ja2V0LmdldGFkZHJpbmZvKCJ3bGYuY29tIiwgODAsIHNvY2tldC5BRl9JTkVUKVswXVs0XVswXQogICAgICAgICAgICA9PSAiMTkyLjE2OC41MC41MCIKICAgICAgICApOgogICAgICAgICAgICBleHBpcmVfYXQgPSBkdC5kYXRlKDk5OTksIDEsIDEpCiAgICBleGNlcHQ6CiAgICAgICAgcGFzcwoKICAgIHd1bGlmYW5nLm1lc3NhZ2UuaW5mbygKICAgICAgICAiXG4iLmpvaW4oCiAgICAgICAgICAgIFsKICAgICAgICAgICAgICAgICLlkL7nq4vmlrnmj5Lku7Ygdnt977yIe33vvIkiLmZvcm1hdCgKICAgICAgICAgICAgICAgICAgICBfX3ZlcnNpb25fXy5WRVJTSU9OLAogICAgICAgICAgICAgICAgICAgIF9fdmVyc2lvbl9fLlJFTEVBU0VfREFURSwKICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAi6K645Y+v6IezOiB7fSIuZm9ybWF0KGV4cGlyZV9hdCksCiAgICAgICAgICAgIF0KICAgICAgICApCiAgICApCiAgICBpZiBleHBpcmVfYXQgPCBkdC5kYXRlLnRvZGF5KCk6CiAgICAgICAgd3VsaWZhbmcubWVzc2FnZS5pbmZvKAogICAgICAgICAgICAi6K645Y+v5bey6L+H5pyfLCDor7fogZTns7vkvZzogIXojrflj5bmm7TmlrDorrjlj69cbuimgeWNuOi9veivt+ebtOaOpeWIoOmZpOaWh+S7tuWkuTp7fSIuZm9ybWF0KAogICAgICAgICAgICAgICAgb3MucGF0aC5hYnNwYXRoKG9zLnBhdGguam9pbihfX2ZpbGVfXywgIi4uLy4uLyIpKQogICAgICAgICAgICApLAogICAgICAgICAgICB0aXRsZT0i5ZC+56uL5pa55o+S5Lu2IiwKICAgICAgICApCiAgICAgCiAgICAgICAgcmFpc2UgTGljZW5zZUVycm9yKCkK"
        ),
        __file__,
        "exec",
    ),
)
