# -*- coding=UTF-8 -*-
# This typing file was generated by typing_from_help.py
# pyright: reportUndefinedVariable=information
"""
hiero.__init__ - # Redirect output to both console and script editor

"""


__all__: ...
"""
['FnPythonFixes', 'FnRedirect', '__builtins__', '__doc__', '...
"""

