from typing import Iterator, Protocol, Text

class FileService(Protocol):
    def exists(self, path: Text, max_age: float = ...) -> bool: ...
    def missing_frames(
        self, filename: Text, first: int, last: int, *, max_age: float = ...
    ) -> Iterator[int]: ...
