# -*- coding=UTF-8 -*-
# This typing file was generated by typing_from_help.py
"""
Qt.QtHelp
"""

import six
import typing
import PySide
import Shiboken

class QHelpContentItem(Shiboken.Object):
    def __copy__(self, *args, **kwargs):
        """ """
        ...
    def child(self, *args, **kwargs):
        """ """
        ...
    def childCount(self, *args, **kwargs):
        """ """
        ...
    def childPosition(self, *args, **kwargs):
        """ """
        ...
    def parent(self, *args, **kwargs):
        """ """
        ...
    def row(self, *args, **kwargs):
        """ """
        ...
    def title(self, *args, **kwargs):
        """ """
        ...
    def url(self, *args, **kwargs):
        """ """
        ...
    ...

class QHelpContentModel(PySide.QtCore.QAbstractItemModel):
    contentsCreated: ...
    """
    Signal
    """

    contentsCreationStarted: ...
    """
    Signal
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """
    def columnCount(self, *args, **kwargs):
        """ """
        ...
    def contentItemAt(self, *args, **kwargs):
        """ """
        ...
    def createContents(self, *args, **kwargs):
        """ """
        ...
    def data(self, *args, **kwargs):
        """ """
        ...
    def index(self, *args, **kwargs):
        """ """
        ...
    def isCreatingContents(self, *args, **kwargs):
        """ """
        ...
    def parent(self, *args, **kwargs):
        """ """
        ...
    def rowCount(self, *args, **kwargs):
        """ """
        ...
    ...

class QHelpContentWidget(PySide.QtGui.QTreeView):
    linkActivated: ...
    """
    Signal
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """
    def indexOf(self, *args, **kwargs):
        """ """
        ...
    ...

class QHelpEngine(QHelpEngineCore):
    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """
    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...
    def contentModel(self, *args, **kwargs):
        """ """
        ...
    def contentWidget(self, *args, **kwargs):
        """ """
        ...
    def indexModel(self, *args, **kwargs):
        """ """
        ...
    def indexWidget(self, *args, **kwargs):
        """ """
        ...
    def searchEngine(self, *args, **kwargs):
        """ """
        ...
    ...

class QHelpEngineCore(PySide.QtCore.QObject):
    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    currentFilterChanged: ...
    """
    Signal
    """

    setupFinished: ...
    """
    Signal
    """

    setupStarted: ...
    """
    Signal
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """

    warning: ...
    """
    Signal
    """
    @staticmethod
    def metaData(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def namespaceName(*args, **kwargs):
        """ """
        ...
    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...
    def addCustomFilter(self, *args, **kwargs):
        """ """
        ...
    def autoSaveFilter(self, *args, **kwargs):
        """ """
        ...
    def collectionFile(self, *args, **kwargs):
        """ """
        ...
    def copyCollectionFile(self, *args, **kwargs):
        """ """
        ...
    def currentFilter(self, *args, **kwargs):
        """ """
        ...
    def customFilters(self, *args, **kwargs):
        """ """
        ...
    def customValue(self, *args, **kwargs):
        """ """
        ...
    def documentationFileName(self, *args, **kwargs):
        """ """
        ...
    def error(self, *args, **kwargs):
        """ """
        ...
    def fileData(self, *args, **kwargs):
        """ """
        ...
    def files(self, *args, **kwargs):
        """ """
        ...
    def filterAttributeSets(self, *args, **kwargs):
        """ """
        ...
    def filterAttributes(self, *args, **kwargs):
        """ """
        ...
    def findFile(self, *args, **kwargs):
        """ """
        ...
    def linksForIdentifier(self, *args, **kwargs):
        """ """
        ...
    def registerDocumentation(self, *args, **kwargs):
        """ """
        ...
    def registeredDocumentations(self, *args, **kwargs):
        """ """
        ...
    def removeCustomFilter(self, *args, **kwargs):
        """ """
        ...
    def removeCustomValue(self, *args, **kwargs):
        """ """
        ...
    def setAutoSaveFilter(self, *args, **kwargs):
        """ """
        ...
    def setCollectionFile(self, *args, **kwargs):
        """ """
        ...
    def setCurrentFilter(self, *args, **kwargs):
        """ """
        ...
    def setCustomValue(self, *args, **kwargs):
        """ """
        ...
    def setupData(self, *args, **kwargs):
        """ """
        ...
    def unregisterDocumentation(self, *args, **kwargs):
        """ """
        ...
    ...

class QHelpIndexModel(PySide.QtGui.QStringListModel):
    indexCreated: ...
    """
    Signal
    """

    indexCreationStarted: ...
    """
    Signal
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """
    def createIndex(self, *args, **kwargs):
        """ """
        ...
    def filter(self, *args, **kwargs):
        """ """
        ...
    def isCreatingIndex(self, *args, **kwargs):
        """ """
        ...
    def linksForKeyword(self, *args, **kwargs):
        """ """
        ...
    ...

class QHelpIndexWidget(PySide.QtGui.QListView):
    linkActivated: ...
    """
    Signal
    """

    linksActivated: ...
    """
    Signal
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """
    def activateCurrentItem(self, *args, **kwargs):
        """ """
        ...
    def filterIndices(self, *args, **kwargs):
        """ """
        ...
    ...

class QHelpSearchEngine(PySide.QtCore.QObject):
    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    indexingFinished: ...
    """
    Signal
    """

    indexingStarted: ...
    """
    Signal
    """

    searchingFinished: ...
    """
    Signal
    """

    searchingStarted: ...
    """
    Signal
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """
    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...
    def cancelIndexing(self, *args, **kwargs):
        """ """
        ...
    def cancelSearching(self, *args, **kwargs):
        """ """
        ...
    def hitCount(self, *args, **kwargs):
        """ """
        ...
    def hits(self, *args, **kwargs):
        """ """
        ...
    def hitsCount(self, *args, **kwargs):
        """ """
        ...
    def query(self, *args, **kwargs):
        """ """
        ...
    def queryWidget(self, *args, **kwargs):
        """ """
        ...
    def reindexDocumentation(self, *args, **kwargs):
        """ """
        ...
    def resultWidget(self, *args, **kwargs):
        """ """
        ...
    def search(self, *args, **kwargs):
        """ """
        ...
    ...

class QHelpSearchQuery(Shiboken.Object):
    ALL: ... = PySide.QtHelp.QHelpSearchQuery.FieldName.ALL
    """
    """

    ATLEAST: ... = PySide.QtHelp.QHelpSearchQuery.FieldName.ATLEAST
    """
    """

    DEFAULT: ... = PySide.QtHelp.QHelpSearchQuery.FieldName.DEFAULT
    """
    """

    FUZZY: ... = PySide.QtHelp.QHelpSearchQuery.FieldName.FUZZY
    """
    """

    FieldName: ...
    """
    <type 'PySide.QtHelp.QHelpSearchQuery.FieldName'>
    """

    PHRASE: ... = PySide.QtHelp.QHelpSearchQuery.FieldName.PHRASE
    """
    """

    WITHOUT: ... = PySide.QtHelp.QHelpSearchQuery.FieldName.WITHOUT
    """
    """

    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """
    def __copy__(self, *args, **kwargs):
        """ """
        ...
    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...
    ...

class QHelpSearchQueryWidget(PySide.QtGui.QWidget):
    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    search: ...
    """
    Signal
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """
    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...
    def changeEvent(self, *args, **kwargs):
        """ """
        ...
    def collapseExtendedSearch(self, *args, **kwargs):
        """ """
        ...
    def expandExtendedSearch(self, *args, **kwargs):
        """ """
        ...
    def focusInEvent(self, *args, **kwargs):
        """ """
        ...
    def query(self, *args, **kwargs):
        """ """
        ...
    def setQuery(self, *args, **kwargs):
        """ """
        ...
    ...

class QHelpSearchResultWidget(PySide.QtGui.QWidget):
    requestShowLink: ...
    """
    Signal
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """
    def changeEvent(self, *args, **kwargs):
        """ """
        ...
    def linkAt(self, *args, **kwargs):
        """ """
        ...
    ...

__all__: ...
"""
['QHelpContentItem', 'QHelpContentModel', 'QHelpContentWidge...
"""
