# -*- coding=UTF-8 -*-
# This typing file was generated by typing_from_help.py
"""
Qt.QtPrintSupport
"""

import six
import typing
import PySide
import Shiboken
from . import QtWidgets, QtGui
class QAbstractPrintDialog(QtWidgets.QDialog):
    AllPages: ... = PySide.QtGui.QAbstractPrintDialog.PrintRange.AllPages
    """
    """

    CurrentPage: ... = PySide.QtGui.QAbstractPrintDialog.PrintRange.CurrentPage
    """
    """

    DontUseSheet: ...
    """
    PySide.QtGui.QAbstractPrintDialog.PrintDialogOption.Don...
    """

    # None: ... = PySide.QtGui.QAbstractPrintDialog.PrintDialogOption.None

    PageRange: ... = PySide.QtGui.QAbstractPrintDialog.PrintRange.PageRange
    """
    """

    PrintCollateCopies: ...
    """
    PySide.QtGui.QAbstractPrintDialog.PrintDialogOpti...
    """

    PrintCurrentPage: ...
    """
    PySide.QtGui.QAbstractPrintDialog.PrintDialogOption...
    """

    PrintDialogOption: ...
    """
    <type 'PySide.QtGui.QAbstractPrintDialog.PrintDial...
    """

    PrintDialogOptions: ...
    """
    <type 'PrintDialogOptions'>
    """

    PrintPageRange: ...
    """
    PySide.QtGui.QAbstractPrintDialog.PrintDialogOption.P...
    """

    PrintRange: ...
    """
    <type 'PySide.QtGui.QAbstractPrintDialog.PrintRange'>
    """

    PrintSelection: ...
    """
    PySide.QtGui.QAbstractPrintDialog.PrintDialogOption.P...
    """

    PrintShowPageSize: ...
    """
    PySide.QtGui.QAbstractPrintDialog.PrintDialogOptio...
    """

    PrintToFile: ...
    """
    PySide.QtGui.QAbstractPrintDialog.PrintDialogOption.Prin...
    """

    Selection: ... = PySide.QtGui.QAbstractPrintDialog.PrintRange.Selection
    """
    """

    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """

    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...

    def addEnabledOption(self, *args, **kwargs):
        """
        """
        ...

    def enabledOptions(self, *args, **kwargs):
        """
        """
        ...

    def exec_(self, *args, **kwargs):
        """
        """
        ...

    def fromPage(self, *args, **kwargs):
        """
        """
        ...

    def isOptionEnabled(self, *args, **kwargs):
        """
        """
        ...

    def maxPage(self, *args, **kwargs):
        """
        """
        ...

    def minPage(self, *args, **kwargs):
        """
        """
        ...

    def printRange(self, *args, **kwargs):
        """
        """
        ...

    def printer(self, *args, **kwargs):
        """
        """
        ...

    def setEnabledOptions(self, *args, **kwargs):
        """
        """
        ...

    def setFromTo(self, *args, **kwargs):
        """
        """
        ...

    def setMinMax(self, *args, **kwargs):
        """
        """
        ...

    def setOptionTabs(self, *args, **kwargs):
        """
        """
        ...

    def setPrintRange(self, *args, **kwargs):
        """
        """
        ...

    def toPage(self, *args, **kwargs):
        """
        """
        ...

    ...

class QPageSetupDialog(QAbstractPageSetupDialog):
    DontUseSheet: ...
    """
    PySide.QtGui.QPageSetupDialog.PageSetupDialogOption.Don...
    """

    # None: ... = PySide.QtGui.QPageSetupDialog.PageSetupDialogOption.None

    OwnsPrinter: ...
    """
    PySide.QtGui.QPageSetupDialog.PageSetupDialogOption.Owns...
    """

    PageSetupDialogOption: ...
    """
    <type 'PySide.QtGui.QPageSetupDialog.PageSetup...
    """

    PageSetupDialogOptions: ...
    """
    <type 'PageSetupDialogOptions'>
    """

    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """

    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...

    def addEnabledOption(self, *args, **kwargs):
        """
        """
        ...

    def enabledOptions(self, *args, **kwargs):
        """
        """
        ...

    def exec_(self, *args, **kwargs):
        """
        """
        ...

    def isOptionEnabled(self, *args, **kwargs):
        """
        """
        ...

    def open(self, *args, **kwargs):
        """
        """
        ...

    def options(self, *args, **kwargs):
        """
        """
        ...

    def setEnabledOptions(self, *args, **kwargs):
        """
        """
        ...

    def setOption(self, *args, **kwargs):
        """
        """
        ...

    def setOptions(self, *args, **kwargs):
        """
        """
        ...

    def testOption(self, *args, **kwargs):
        """
        """
        ...

    ...

class QPrintDialog(QAbstractPrintDialog):
    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    accepted: ...
    """
    Signal
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """

    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...

    def done(self, *args, **kwargs):
        """
        """
        ...

    def exec_(self, *args, **kwargs):
        """
        """
        ...

    def open(self, *args, **kwargs):
        """
        """
        ...

    def options(self, *args, **kwargs):
        """
        """
        ...

    def setOption(self, *args, **kwargs):
        """
        """
        ...

    def setOptions(self, *args, **kwargs):
        """
        """
        ...

    def testOption(self, *args, **kwargs):
        """
        """
        ...

    ...

class QPrintEngine(Shiboken.Object):
    PPK_CollateCopies: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.P...
    """

    PPK_ColorMode: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_C...
    """

    PPK_CopyCount: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_C...
    """

    PPK_Creator: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_Cre...
    """

    PPK_CustomBase: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_...
    """

    PPK_CustomPaperSize: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey...
    """

    PPK_DocumentName: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PP...
    """

    PPK_Duplex: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_Dupl...
    """

    PPK_FontEmbedding: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.P...
    """

    PPK_FullPage: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_Fu...
    """

    PPK_NumberOfCopies: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey....
    """

    PPK_Orientation: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK...
    """

    PPK_OutputFileName: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey....
    """

    PPK_PageMargins: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK...
    """

    PPK_PageOrder: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_P...
    """

    PPK_PageRect: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_Pa...
    """

    PPK_PageSize: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_Pa...
    """

    PPK_PaperRect: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_P...
    """

    PPK_PaperSize: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_P...
    """

    PPK_PaperSource: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK...
    """

    PPK_PaperSources: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PP...
    """

    PPK_PrinterName: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK...
    """

    PPK_PrinterProgram: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey....
    """

    PPK_Resolution: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey.PPK_...
    """

    PPK_SelectionOption: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey...
    """

    PPK_SupportedResolutions: ...
    """
    PySide.QtGui.QPrintEngine.PrintEngineProper...
    """

    PPK_SupportsMultipleCopies: ...
    """
    PySide.QtGui.QPrintEngine.PrintEngineProp...
    """

    PPK_SuppressSystemPrintStatus: ...
    """
    PySide.QtGui.QPrintEngine.PrintEngineP...
    """

    PPK_WindowsPageSize: ...
    """
    PySide.QtGui.QPrintEngine.PrintEnginePropertyKey...
    """

    PrintEnginePropertyKey: ...
    """
    <type 'PySide.QtGui.QPrintEngine.PrintEngineP...
    """

    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...

    def abort(self, *args, **kwargs):
        """
        """
        ...

    def metric(self, *args, **kwargs):
        """
        """
        ...

    def newPage(self, *args, **kwargs):
        """
        """
        ...

    def printerState(self, *args, **kwargs):
        """
        """
        ...

    def property(self, *args, **kwargs):
        """
        """
        ...

    def setProperty(self, *args, **kwargs):
        """
        """
        ...

    ...

class QPrintPreviewDialog(QDialog):
    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    paintRequested: ...
    """
    Signal
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """

    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...

    def done(self, *args, **kwargs):
        """
        """
        ...

    def open(self, *args, **kwargs):
        """
        """
        ...

    def printer(self, *args, **kwargs):
        """
        """
        ...

    def setVisible(self, *args, **kwargs):
        """
        """
        ...

    ...

class QPrintPreviewWidget(QtWidgets.QWidget):
    AllPagesView: ... = PySide.QtGui.QPrintPreviewWidget.ViewMode.AllPagesView
    """
    """

    CustomZoom: ... = PySide.QtGui.QPrintPreviewWidget.ZoomMode.CustomZoom
    """
    """

    FacingPagesView: ...
    """
    PySide.QtGui.QPrintPreviewWidget.ViewMode.FacingPage...
    """

    FitInView: ... = PySide.QtGui.QPrintPreviewWidget.ZoomMode.FitInView
    """
    """

    FitToWidth: ... = PySide.QtGui.QPrintPreviewWidget.ZoomMode.FitToWidth
    """
    """

    SinglePageView: ...
    """
    PySide.QtGui.QPrintPreviewWidget.ViewMode.SinglePageV...
    """

    ViewMode: ...
    """
    <type 'PySide.QtGui.QPrintPreviewWidget.ViewMode'>
    """

    ZoomMode: ...
    """
    <type 'PySide.QtGui.QPrintPreviewWidget.ZoomMode'>
    """

    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    paintRequested: ...
    """
    Signal
    """

    previewChanged: ...
    """
    Signal
    """

    staticMetaObject: ...
    """
    <PySide.QtCore.QMetaObject object>
    """

    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...

    def currentPage(self, *args, **kwargs):
        """
        """
        ...

    def fitInView(self, *args, **kwargs):
        """
        """
        ...

    def fitToWidth(self, *args, **kwargs):
        """
        """
        ...

    def numPages(self, *args, **kwargs):
        """
        """
        ...

    def orientation(self, *args, **kwargs):
        """
        """
        ...

    def pageCount(self, *args, **kwargs):
        """
        """
        ...

    def print_(self, *args, **kwargs):
        """
        """
        ...

    def setAllPagesViewMode(self, *args, **kwargs):
        """
        """
        ...

    def setCurrentPage(self, *args, **kwargs):
        """
        """
        ...

    def setFacingPagesViewMode(self, *args, **kwargs):
        """
        """
        ...

    def setLandscapeOrientation(self, *args, **kwargs):
        """
        """
        ...

    def setOrientation(self, *args, **kwargs):
        """
        """
        ...

    def setPortraitOrientation(self, *args, **kwargs):
        """
        """
        ...

    def setSinglePageViewMode(self, *args, **kwargs):
        """
        """
        ...

    def setViewMode(self, *args, **kwargs):
        """
        """
        ...

    def setVisible(self, *args, **kwargs):
        """
        """
        ...

    def setZoomFactor(self, *args, **kwargs):
        """
        """
        ...

    def setZoomMode(self, *args, **kwargs):
        """
        """
        ...

    def updatePreview(self, *args, **kwargs):
        """
        """
        ...

    def viewMode(self, *args, **kwargs):
        """
        """
        ...

    def zoomFactor(self, *args, **kwargs):
        """
        """
        ...

    def zoomIn(self, *args, **kwargs):
        """
        """
        ...

    def zoomMode(self, *args, **kwargs):
        """
        """
        ...

    def zoomOut(self, *args, **kwargs):
        """
        """
        ...

    ...

class QPrinter(QtGui.QPaintDevice):
    A0: ... = PySide.QtGui.QPrinter.PageSize.A0
    """
    """

    A1: ... = PySide.QtGui.QPrinter.PageSize.A1
    """
    """

    A2: ... = PySide.QtGui.QPrinter.PageSize.A2
    """
    """

    A3: ... = PySide.QtGui.QPrinter.PageSize.A3
    """
    """

    A4: ... = PySide.QtGui.QPrinter.PageSize.A4
    """
    """

    A5: ... = PySide.QtGui.QPrinter.PageSize.A5
    """
    """

    A6: ... = PySide.QtGui.QPrinter.PageSize.A6
    """
    """

    A7: ... = PySide.QtGui.QPrinter.PageSize.A7
    """
    """

    A8: ... = PySide.QtGui.QPrinter.PageSize.A8
    """
    """

    A9: ... = PySide.QtGui.QPrinter.PageSize.A9
    """
    """

    Aborted: ... = PySide.QtGui.QPrinter.PrinterState.Aborted
    """
    """

    Active: ... = PySide.QtGui.QPrinter.PrinterState.Active
    """
    """

    AllPages: ... = PySide.QtGui.QPrinter.PrintRange.AllPages
    """
    """

    Auto: ... = PySide.QtGui.QPrinter.PaperSource.Auto
    """
    """

    B0: ... = PySide.QtGui.QPrinter.PageSize.B0
    """
    """

    B1: ... = PySide.QtGui.QPrinter.PageSize.B1
    """
    """

    B10: ... = PySide.QtGui.QPrinter.PageSize.B10
    """
    """

    B2: ... = PySide.QtGui.QPrinter.PageSize.B2
    """
    """

    B3: ... = PySide.QtGui.QPrinter.PageSize.B3
    """
    """

    B4: ... = PySide.QtGui.QPrinter.PageSize.B4
    """
    """

    B5: ... = PySide.QtGui.QPrinter.PageSize.B5
    """
    """

    B6: ... = PySide.QtGui.QPrinter.PageSize.B6
    """
    """

    B7: ... = PySide.QtGui.QPrinter.PageSize.B7
    """
    """

    B8: ... = PySide.QtGui.QPrinter.PageSize.B8
    """
    """

    B9: ... = PySide.QtGui.QPrinter.PageSize.B9
    """
    """

    C5E: ... = PySide.QtGui.QPrinter.PageSize.C5E
    """
    """

    Cassette: ... = PySide.QtGui.QPrinter.PaperSource.Cassette
    """
    """

    Cicero: ... = PySide.QtGui.QPrinter.Unit.Cicero
    """
    """

    Color: ... = PySide.QtGui.QPrinter.ColorMode.Color
    """
    """

    ColorMode: ...
    """
    <type 'PySide.QtGui.QPrinter.ColorMode'>
    """

    Comm10E: ... = PySide.QtGui.QPrinter.PageSize.Comm10E
    """
    """

    CurrentPage: ... = PySide.QtGui.QPrinter.PrintRange.CurrentPage
    """
    """

    Custom: ... = PySide.QtGui.QPrinter.PageSize.Custom
    """
    """

    DLE: ... = PySide.QtGui.QPrinter.PageSize.DLE
    """
    """

    DevicePixel: ... = PySide.QtGui.QPrinter.Unit.DevicePixel
    """
    """

    Didot: ... = PySide.QtGui.QPrinter.Unit.Didot
    """
    """

    DuplexAuto: ... = PySide.QtGui.QPrinter.DuplexMode.DuplexAuto
    """
    """

    DuplexLongSide: ... = PySide.QtGui.QPrinter.DuplexMode.DuplexLongSide
    """
    """

    DuplexMode: ...
    """
    <type 'PySide.QtGui.QPrinter.DuplexMode'>
    """

    DuplexNone: ... = PySide.QtGui.QPrinter.DuplexMode.DuplexNone
    """
    """

    DuplexShortSide: ... = PySide.QtGui.QPrinter.DuplexMode.DuplexShortSide
    """
    """

    Envelope: ... = PySide.QtGui.QPrinter.PaperSource.Envelope
    """
    """

    EnvelopeManual: ... = PySide.QtGui.QPrinter.PaperSource.EnvelopeManual
    """
    """

    Error: ... = PySide.QtGui.QPrinter.PrinterState.Error
    """
    """

    Executive: ... = PySide.QtGui.QPrinter.PageSize.Executive
    """
    """

    FirstPageFirst: ... = PySide.QtGui.QPrinter.PageOrder.FirstPageFirst
    """
    """

    Folio: ... = PySide.QtGui.QPrinter.PageSize.Folio
    """
    """

    FormSource: ... = PySide.QtGui.QPrinter.PaperSource.FormSource
    """
    """

    GrayScale: ... = PySide.QtGui.QPrinter.ColorMode.GrayScale
    """
    """

    HighResolution: ... = PySide.QtGui.QPrinter.PrinterMode.HighResolution
    """
    """

    Idle: ... = PySide.QtGui.QPrinter.PrinterState.Idle
    """
    """

    Inch: ... = PySide.QtGui.QPrinter.Unit.Inch
    """
    """

    Landscape: ... = PySide.QtGui.QPrinter.Orientation.Landscape
    """
    """

    LargeCapacity: ... = PySide.QtGui.QPrinter.PaperSource.LargeCapacity
    """
    """

    LargeFormat: ... = PySide.QtGui.QPrinter.PaperSource.LargeFormat
    """
    """

    LastPageFirst: ... = PySide.QtGui.QPrinter.PageOrder.LastPageFirst
    """
    """

    Ledger: ... = PySide.QtGui.QPrinter.PageSize.Ledger
    """
    """

    Legal: ... = PySide.QtGui.QPrinter.PageSize.Legal
    """
    """

    Letter: ... = PySide.QtGui.QPrinter.PageSize.Letter
    """
    """

    Lower: ... = PySide.QtGui.QPrinter.PaperSource.Lower
    """
    """

    Manual: ... = PySide.QtGui.QPrinter.PaperSource.Manual
    """
    """

    MaxPageSource: ... = PySide.QtGui.QPrinter.PaperSource.MaxPageSource
    """
    """

    Middle: ... = PySide.QtGui.QPrinter.PaperSource.Middle
    """
    """

    Millimeter: ... = PySide.QtGui.QPrinter.Unit.Millimeter
    """
    """

    NPageSize: ... = PySide.QtGui.QPrinter.PageSize.NPageSize
    """
    """

    NPaperSize: ... = PySide.QtGui.QPrinter.PageSize.NPaperSize
    """
    """

    NativeFormat: ... = PySide.QtGui.QPrinter.OutputFormat.NativeFormat
    """
    """

    OnlyOne: ... = PySide.QtGui.QPrinter.PaperSource.OnlyOne
    """
    """

    Orientation: ...
    """
    <type 'PySide.QtGui.QPrinter.Orientation'>
    """

    OutputFormat: ...
    """
    <type 'PySide.QtGui.QPrinter.OutputFormat'>
    """

    PageOrder: ...
    """
    <type 'PySide.QtGui.QPrinter.PageOrder'>
    """

    PageRange: ... = PySide.QtGui.QPrinter.PrintRange.PageRange
    """
    """

    PageSize: ...
    """
    <type 'PySide.QtGui.QPrinter.PageSize'>
    """

    PaperSource: ...
    """
    <type 'PySide.QtGui.QPrinter.PaperSource'>
    """

    PdfFormat: ... = PySide.QtGui.QPrinter.OutputFormat.PdfFormat
    """
    """

    Pica: ... = PySide.QtGui.QPrinter.Unit.Pica
    """
    """

    Point: ... = PySide.QtGui.QPrinter.Unit.Point
    """
    """

    Portrait: ... = PySide.QtGui.QPrinter.Orientation.Portrait
    """
    """

    PostScriptFormat: ... = PySide.QtGui.QPrinter.OutputFormat.PostScriptFormat
    """
    """

    PrintRange: ...
    """
    <type 'PySide.QtGui.QPrinter.PrintRange'>
    """

    PrinterMode: ...
    """
    <type 'PySide.QtGui.QPrinter.PrinterMode'>
    """

    PrinterResolution: ...
    """
    PySide.QtGui.QPrinter.PrinterMode.PrinterResolutio...
    """

    PrinterState: ...
    """
    <type 'PySide.QtGui.QPrinter.PrinterState'>
    """

    ScreenResolution: ... = PySide.QtGui.QPrinter.PrinterMode.ScreenResolution
    """
    """

    Selection: ... = PySide.QtGui.QPrinter.PrintRange.Selection
    """
    """

    SmallFormat: ... = PySide.QtGui.QPrinter.PaperSource.SmallFormat
    """
    """

    Tabloid: ... = PySide.QtGui.QPrinter.PageSize.Tabloid
    """
    """

    Tractor: ... = PySide.QtGui.QPrinter.PaperSource.Tractor
    """
    """

    Unit: ...
    """
    <type 'PySide.QtGui.QPrinter.Unit'>
    """

    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...

    def abort(self, *args, **kwargs):
        """
        """
        ...

    def actualNumCopies(self, *args, **kwargs):
        """
        """
        ...

    def collateCopies(self, *args, **kwargs):
        """
        """
        ...

    def colorMode(self, *args, **kwargs):
        """
        """
        ...

    def copyCount(self, *args, **kwargs):
        """
        """
        ...

    def creator(self, *args, **kwargs):
        """
        """
        ...

    def devType(self, *args, **kwargs):
        """
        """
        ...

    def docName(self, *args, **kwargs):
        """
        """
        ...

    def doubleSidedPrinting(self, *args, **kwargs):
        """
        """
        ...

    def duplex(self, *args, **kwargs):
        """
        """
        ...

    def fontEmbeddingEnabled(self, *args, **kwargs):
        """
        """
        ...

    def fromPage(self, *args, **kwargs):
        """
        """
        ...

    def fullPage(self, *args, **kwargs):
        """
        """
        ...

    def getPageMargins(self, *args, **kwargs):
        """
        """
        ...

    def isValid(self, *args, **kwargs):
        """
        """
        ...

    def metric(self, *args, **kwargs):
        """
        """
        ...

    def newPage(self, *args, **kwargs):
        """
        """
        ...

    def numCopies(self, *args, **kwargs):
        """
        """
        ...

    def orientation(self, *args, **kwargs):
        """
        """
        ...

    def outputFileName(self, *args, **kwargs):
        """
        """
        ...

    def outputFormat(self, *args, **kwargs):
        """
        """
        ...

    def pageOrder(self, *args, **kwargs):
        """
        """
        ...

    def pageRect(self, *args, **kwargs):
        """
        """
        ...

    def pageSize(self, *args, **kwargs):
        """
        """
        ...

    def paintEngine(self, *args, **kwargs):
        """
        """
        ...

    def paperRect(self, *args, **kwargs):
        """
        """
        ...

    def paperSize(self, *args, **kwargs):
        """
        """
        ...

    def paperSource(self, *args, **kwargs):
        """
        """
        ...

    def printEngine(self, *args, **kwargs):
        """
        """
        ...

    def printProgram(self, *args, **kwargs):
        """
        """
        ...

    def printRange(self, *args, **kwargs):
        """
        """
        ...

    def printerName(self, *args, **kwargs):
        """
        """
        ...

    def printerState(self, *args, **kwargs):
        """
        """
        ...

    def resolution(self, *args, **kwargs):
        """
        """
        ...

    def setCollateCopies(self, *args, **kwargs):
        """
        """
        ...

    def setColorMode(self, *args, **kwargs):
        """
        """
        ...

    def setCopyCount(self, *args, **kwargs):
        """
        """
        ...

    def setCreator(self, *args, **kwargs):
        """
        """
        ...

    def setDocName(self, *args, **kwargs):
        """
        """
        ...

    def setDoubleSidedPrinting(self, *args, **kwargs):
        """
        """
        ...

    def setDuplex(self, *args, **kwargs):
        """
        """
        ...

    def setEngines(self, *args, **kwargs):
        """
        """
        ...

    def setFontEmbeddingEnabled(self, *args, **kwargs):
        """
        """
        ...

    def setFromTo(self, *args, **kwargs):
        """
        """
        ...

    def setFullPage(self, *args, **kwargs):
        """
        """
        ...

    def setNumCopies(self, *args, **kwargs):
        """
        """
        ...

    def setOrientation(self, *args, **kwargs):
        """
        """
        ...

    def setOutputFileName(self, *args, **kwargs):
        """
        """
        ...

    def setOutputFormat(self, *args, **kwargs):
        """
        """
        ...

    def setPageMargins(self, *args, **kwargs):
        """
        """
        ...

    def setPageOrder(self, *args, **kwargs):
        """
        """
        ...

    def setPageSize(self, *args, **kwargs):
        """
        """
        ...

    def setPaperSize(self, *args, **kwargs):
        """
        """
        ...

    def setPaperSource(self, *args, **kwargs):
        """
        """
        ...

    def setPrintProgram(self, *args, **kwargs):
        """
        """
        ...

    def setPrintRange(self, *args, **kwargs):
        """
        """
        ...

    def setPrinterName(self, *args, **kwargs):
        """
        """
        ...

    def setResolution(self, *args, **kwargs):
        """
        """
        ...

    def setWinPageSize(self, *args, **kwargs):
        """
        """
        ...

    def supportedPaperSources(self, *args, **kwargs):
        """
        """
        ...

    def supportedResolutions(self, *args, **kwargs):
        """
        """
        ...

    def supportsMultipleCopies(self, *args, **kwargs):
        """
        """
        ...

    def toPage(self, *args, **kwargs):
        """
        """
        ...

    def winPageSize(self, *args, **kwargs):
        """
        """
        ...

    ...

class QPrinterInfo(Shiboken.Object):
    __new__: ...
    """
    T.__new__(S, ...) -> a new object with type S, a subtype of T
    """

    @staticmethod
    def availablePrinters(*args, **kwargs):
        """
        """
        ...

    @staticmethod
    def defaultPrinter(*args, **kwargs):
        """
        """
        ...

    def __copy__(self, *args, **kwargs):
        """
        """
        ...

    def __init__(self, *args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...

    def __nonzero__(self, *args, **kwargs):
        """
        x.__nonzero__() <==> x != 0
        """
        ...

    def isDefault(self, *args, **kwargs):
        """
        """
        ...

    def isNull(self, *args, **kwargs):
        """
        """
        ...

    def printerName(self, *args, **kwargs):
        """
        """
        ...

    def supportedPaperSizes(self, *args, **kwargs):
        """
        """
        ...

    ...

__all__: ...
"""
['QAbstractPrintDialog', 'QPageSetupDialog', 'QPrintDialog',...
"""

