# -*- coding=UTF-8 -*-
# This typing file was generated by typing_from_help.py
"""
Qt.QtTest
"""

import six
import typing
import PySide
import Shiboken

class QTest(Shiboken.Object):
    AI_Description: ... = PySide.QtTest.QTest.AttributeIndex.AI_Description
    """
    """

    AI_Errors: ... = PySide.QtTest.QTest.AttributeIndex.AI_Errors
    """
    """

    AI_Failures: ... = PySide.QtTest.QTest.AttributeIndex.AI_Failures
    """
    """

    AI_File: ... = PySide.QtTest.QTest.AttributeIndex.AI_File
    """
    """

    AI_Iterations: ... = PySide.QtTest.QTest.AttributeIndex.AI_Iterations
    """
    """

    AI_Line: ... = PySide.QtTest.QTest.AttributeIndex.AI_Line
    """
    """

    AI_Metric: ... = PySide.QtTest.QTest.AttributeIndex.AI_Metric
    """
    """

    AI_Name: ... = PySide.QtTest.QTest.AttributeIndex.AI_Name
    """
    """

    AI_PropertyValue: ... = PySide.QtTest.QTest.AttributeIndex.AI_PropertyValue
    """
    """

    AI_QTestVersion: ... = PySide.QtTest.QTest.AttributeIndex.AI_QTestVersion
    """
    """

    AI_QtVersion: ... = PySide.QtTest.QTest.AttributeIndex.AI_QtVersion
    """
    """

    AI_Result: ... = PySide.QtTest.QTest.AttributeIndex.AI_Result
    """
    """

    AI_Tag: ... = PySide.QtTest.QTest.AttributeIndex.AI_Tag
    """
    """

    AI_Tests: ... = PySide.QtTest.QTest.AttributeIndex.AI_Tests
    """
    """

    AI_Type: ... = PySide.QtTest.QTest.AttributeIndex.AI_Type
    """
    """

    AI_Undefined: ... = PySide.QtTest.QTest.AttributeIndex.AI_Undefined
    """
    """

    AI_Value: ... = PySide.QtTest.QTest.AttributeIndex.AI_Value
    """
    """

    Abort: ... = PySide.QtTest.QTest.TestFailMode.Abort
    """
    """

    AttributeIndex: ...
    """
    <type 'PySide.QtTest.QTest.AttributeIndex'>
    """

    BitsPerSecond: ... = PySide.QtTest.QTest.QBenchmarkMetric.BitsPerSecond
    """
    """

    BytesPerSecond: ... = PySide.QtTest.QTest.QBenchmarkMetric.BytesPerSecond
    """
    """

    CPUTicks: ... = PySide.QtTest.QTest.QBenchmarkMetric.CPUTicks
    """
    """

    Click: ... = PySide.QtTest.QTest.KeyAction.Click
    """
    """

    Continue: ... = PySide.QtTest.QTest.TestFailMode.Continue
    """
    """

    Events: ... = PySide.QtTest.QTest.QBenchmarkMetric.Events
    """
    """

    FramesPerSecond: ... = PySide.QtTest.QTest.QBenchmarkMetric.FramesPerSecond
    """
    """

    InstructionReads: ...
    """
    PySide.QtTest.QTest.QBenchmarkMetric.InstructionRea...
    """

    KeyAction: ...
    """
    <type 'PySide.QtTest.QTest.KeyAction'>
    """

    LET_Benchmark: ... = PySide.QtTest.QTest.LogElementType.LET_Benchmark
    """
    """

    LET_Error: ... = PySide.QtTest.QTest.LogElementType.LET_Error
    """
    """

    LET_Failure: ... = PySide.QtTest.QTest.LogElementType.LET_Failure
    """
    """

    LET_Properties: ... = PySide.QtTest.QTest.LogElementType.LET_Properties
    """
    """

    LET_Property: ... = PySide.QtTest.QTest.LogElementType.LET_Property
    """
    """

    LET_SystemError: ... = PySide.QtTest.QTest.LogElementType.LET_SystemError
    """
    """

    LET_TestCase: ... = PySide.QtTest.QTest.LogElementType.LET_TestCase
    """
    """

    LET_TestSuite: ... = PySide.QtTest.QTest.LogElementType.LET_TestSuite
    """
    """

    LET_Undefined: ... = PySide.QtTest.QTest.LogElementType.LET_Undefined
    """
    """

    LogElementType: ...
    """
    <type 'PySide.QtTest.QTest.LogElementType'>
    """

    MouseAction: ...
    """
    <type 'PySide.QtTest.QTest.MouseAction'>
    """

    MouseClick: ... = PySide.QtTest.QTest.MouseAction.MouseClick
    """
    """

    MouseDClick: ... = PySide.QtTest.QTest.MouseAction.MouseDClick
    """
    """

    MouseMove: ... = PySide.QtTest.QTest.MouseAction.MouseMove
    """
    """

    MousePress: ... = PySide.QtTest.QTest.MouseAction.MousePress
    """
    """

    MouseRelease: ... = PySide.QtTest.QTest.MouseAction.MouseRelease
    """
    """

    Press: ... = PySide.QtTest.QTest.KeyAction.Press
    """
    """

    QBenchmarkMetric: ...
    """
    <type 'PySide.QtTest.QTest.QBenchmarkMetric'>
    """

    QTouchEventSequence: ...
    """
    <type 'PySide.QtTest.QTest.QTouchEventSequence'>
    """

    Release: ... = PySide.QtTest.QTest.KeyAction.Release
    """
    """

    SkipAll: ... = PySide.QtTest.QTest.SkipMode.SkipAll
    """
    """

    SkipMode: ...
    """
    <type 'PySide.QtTest.QTest.SkipMode'>
    """

    SkipSingle: ... = PySide.QtTest.QTest.SkipMode.SkipSingle
    """
    """

    TestFailMode: ...
    """
    <type 'PySide.QtTest.QTest.TestFailMode'>
    """

    WalltimeMilliseconds: ...
    """
    PySide.QtTest.QTest.QBenchmarkMetric.WalltimeMi...
    """
    @staticmethod
    def addColumnInternal(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def asciiToKey(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def compare_ptr_helper(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def compare_string_helper(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def currentDataTag(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def currentTestFailed(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def currentTestFunction(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def ignoreMessage(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def keyClick(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def keyClicks(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def keyEvent(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def keyPress(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def keyRelease(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def keyToAscii(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def mouseClick(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def mouseDClick(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def mouseEvent(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def mouseMove(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def mousePress(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def mouseRelease(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def qElementData(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def qExpectFail(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def qGlobalData(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def qSkip(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def qWaitForWindowShown(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def sendKeyEvent(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def setBenchmarkResult(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def simulateEvent(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def testObject(*args, **kwargs):
        """ """
        ...
    @staticmethod
    def touchEvent(*args, **kwargs):
        """ """
        ...
    ...

__all__: list
"""
['QTest', '__doc__', '__name__']
"""
