# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scenetools_dialog.ui'
#
# Created: Fri Aug 18 10:05:47 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(475, 535)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.toolButtonOpenDir = QtGui.QToolButton(Dialog)
        self.toolButtonOpenDir.setAutoRaise(True)
        self.toolButtonOpenDir.setObjectName("toolButtonOpenDir")
        self.horizontalLayout_5.addWidget(self.toolButtonOpenDir)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dirEdit = QtGui.QLineEdit(Dialog)
        self.dirEdit.setDragEnabled(True)
        self.dirEdit.setObjectName("dirEdit")
        self.horizontalLayout_9.addWidget(self.dirEdit)
        self.dirButton = QtGui.QToolButton(Dialog)
        self.dirButton.setAutoRaise(True)
        self.dirButton.setObjectName("dirButton")
        self.horizontalLayout_9.addWidget(self.dirButton)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.projectEdit = QtGui.QLineEdit(Dialog)
        self.projectEdit.setObjectName("projectEdit")
        self.horizontalLayout_12.addWidget(self.projectEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.epEdit = QtGui.QLineEdit(Dialog)
        self.epEdit.setObjectName("epEdit")
        self.horizontalLayout.addWidget(self.epEdit)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.scEdit = QtGui.QLineEdit(Dialog)
        self.scEdit.setObjectName("scEdit")
        self.horizontalLayout.addWidget(self.scEdit)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.listWidget = QtGui.QListWidget(self.tab)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_7.addWidget(self.listWidget)
        self.toolBox = QtGui.QToolBox(self.tab)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toolBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolBox.setObjectName("toolBox")
        self.toolBoxPage2 = QtGui.QWidget()
        self.toolBoxPage2.setGeometry(QtCore.QRect(0, 0, 211, 292))
        self.toolBoxPage2.setObjectName("toolBoxPage2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.toolBoxPage2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.imageFNameEdit = QtGui.QLineEdit(self.toolBoxPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageFNameEdit.sizePolicy().hasHeightForWidth())
        self.imageFNameEdit.setSizePolicy(sizePolicy)
        self.imageFNameEdit.setObjectName("imageFNameEdit")
        self.gridLayout_2.addWidget(self.imageFNameEdit, 1, 1, 1, 1)
        self.videoFNameEdit = QtGui.QLineEdit(self.toolBoxPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoFNameEdit.sizePolicy().hasHeightForWidth())
        self.videoFNameEdit.setSizePolicy(sizePolicy)
        self.videoFNameEdit.setObjectName("videoFNameEdit")
        self.gridLayout_2.addWidget(self.videoFNameEdit, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.toolBoxPage2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.toolBoxPage2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_16 = QtGui.QLabel(self.toolBoxPage2)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.videoDestEdit = QtGui.QLineEdit(self.toolBoxPage2)
        self.videoDestEdit.setFrame(False)
        self.videoDestEdit.setReadOnly(True)
        self.videoDestEdit.setObjectName("videoDestEdit")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.videoDestEdit)
        self.label_17 = QtGui.QLabel(self.toolBoxPage2)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.imageDestEdit = QtGui.QLineEdit(self.toolBoxPage2)
        self.imageDestEdit.setFrame(False)
        self.imageDestEdit.setReadOnly(True)
        self.imageDestEdit.setObjectName("imageDestEdit")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.imageDestEdit)
        self.verticalLayout_6.addLayout(self.formLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtGui.QLabel(self.toolBoxPage2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.videoUpCheck = QtGui.QCheckBox(self.toolBoxPage2)
        self.videoUpCheck.setObjectName("videoUpCheck")
        self.horizontalLayout_6.addWidget(self.videoUpCheck)
        self.imageUpCheck = QtGui.QCheckBox(self.toolBoxPage2)
        self.imageUpCheck.setObjectName("imageUpCheck")
        self.horizontalLayout_6.addWidget(self.imageUpCheck)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtGui.QLabel(self.toolBoxPage2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.videoDownCheck = QtGui.QCheckBox(self.toolBoxPage2)
        self.videoDownCheck.setEnabled(False)
        self.videoDownCheck.setCheckable(True)
        self.videoDownCheck.setObjectName("videoDownCheck")
        self.horizontalLayout_8.addWidget(self.videoDownCheck)
        self.imageDownCheck = QtGui.QCheckBox(self.toolBoxPage2)
        self.imageDownCheck.setObjectName("imageDownCheck")
        self.horizontalLayout_8.addWidget(self.imageDownCheck)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.syncButton = QtGui.QPushButton(self.toolBoxPage2)
        self.syncButton.setMinimumSize(QtCore.QSize(0, 50))
        self.syncButton.setObjectName("syncButton")
        self.verticalLayout_6.addWidget(self.syncButton)
        self.toolBox.addItem(self.toolBoxPage2, "")
        self.toolBoxPage1 = QtGui.QWidget()
        self.toolBoxPage1.setGeometry(QtCore.QRect(0, 0, 207, 292))
        self.toolBoxPage1.setObjectName("toolBoxPage1")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.toolBoxPage1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_11 = QtGui.QLabel(self.toolBoxPage1)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.csheetFFNameEdit = QtGui.QLineEdit(self.toolBoxPage1)
        self.csheetFFNameEdit.setObjectName("csheetFFNameEdit")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.csheetFFNameEdit)
        self.label_19 = QtGui.QLabel(self.toolBoxPage1)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
        self.csheetPrefixEdit = QtGui.QLineEdit(self.toolBoxPage1)
        self.csheetPrefixEdit.setObjectName("csheetPrefixEdit")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.csheetPrefixEdit)
        self.label_12 = QtGui.QLabel(self.toolBoxPage1)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.backDropBox = QtGui.QComboBox(self.toolBoxPage1)
        self.backDropBox.setObjectName("backDropBox")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.backDropBox)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_18 = QtGui.QLabel(self.toolBoxPage1)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_18)
        self.csheetNameEdit = QtGui.QLineEdit(self.toolBoxPage1)
        self.csheetNameEdit.setFrame(False)
        self.csheetNameEdit.setReadOnly(True)
        self.csheetNameEdit.setObjectName("csheetNameEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.csheetNameEdit)
        self.label_20 = QtGui.QLabel(self.toolBoxPage1)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_20)
        self.csheetDestEdit = QtGui.QLineEdit(self.toolBoxPage1)
        self.csheetDestEdit.setFrame(False)
        self.csheetDestEdit.setReadOnly(True)
        self.csheetDestEdit.setObjectName("csheetDestEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.csheetDestEdit)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.csheetOpenCheck = QtGui.QCheckBox(self.toolBoxPage1)
        self.csheetOpenCheck.setObjectName("csheetOpenCheck")
        self.verticalLayout_3.addWidget(self.csheetOpenCheck)
        self.csheetUpCheck = QtGui.QCheckBox(self.toolBoxPage1)
        self.csheetUpCheck.setObjectName("csheetUpCheck")
        self.verticalLayout_3.addWidget(self.csheetUpCheck)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.sheetButton = QtGui.QPushButton(self.toolBoxPage1)
        self.sheetButton.setMinimumSize(QtCore.QSize(0, 50))
        self.sheetButton.setObjectName("sheetButton")
        self.verticalLayout_3.addWidget(self.sheetButton)
        self.openButton = QtGui.QPushButton(self.toolBoxPage1)
        self.openButton.setEnabled(True)
        self.openButton.setObjectName("openButton")
        self.verticalLayout_3.addWidget(self.openButton)
        self.toolBox.addItem(self.toolBoxPage1, "")
        self.horizontalLayout_7.addWidget(self.toolBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.toolButtonOpenServer = QtGui.QToolButton(self.tab_2)
        self.toolButtonOpenServer.setAutoRaise(True)
        self.toolButtonOpenServer.setObjectName("toolButtonOpenServer")
        self.horizontalLayout_4.addWidget(self.toolButtonOpenServer)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.serverEdit = QtGui.QLineEdit(self.tab_2)
        self.serverEdit.setDragEnabled(True)
        self.serverEdit.setObjectName("serverEdit")
        self.horizontalLayout_3.addWidget(self.serverEdit)
        self.serverButton = QtGui.QToolButton(self.tab_2)
        self.serverButton.setAutoRaise(True)
        self.serverButton.setObjectName("serverButton")
        self.horizontalLayout_3.addWidget(self.serverButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.videoFolderEdit = QtGui.QLineEdit(self.tab_2)
        self.videoFolderEdit.setObjectName("videoFolderEdit")
        self.gridLayout.addWidget(self.videoFolderEdit, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.imageFolderEdit = QtGui.QLineEdit(self.tab_2)
        self.imageFolderEdit.setObjectName("imageFolderEdit")
        self.gridLayout.addWidget(self.imageFolderEdit, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(self.tab_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nukeEdit = QtGui.QLineEdit(self.tab_2)
        self.nukeEdit.setDragEnabled(True)
        self.nukeEdit.setObjectName("nukeEdit")
        self.horizontalLayout_2.addWidget(self.nukeEdit)
        self.nukeButton = QtGui.QToolButton(self.tab_2)
        self.nukeButton.setAutoRaise(True)
        self.nukeButton.setObjectName("nukeButton")
        self.horizontalLayout_2.addWidget(self.nukeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(20, 184, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.version_label = QtGui.QLabel(Dialog)
        self.version_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_label.setObjectName("version_label")
        self.verticalLayout.addWidget(self.version_label)
        self.actionSheet = QtGui.QAction(Dialog)
        self.actionSheet.setObjectName("actionSheet")
        self.actionSync = QtGui.QAction(Dialog)
        self.actionSync.setObjectName("actionSync")
        self.actionOpen = QtGui.QAction(Dialog)
        self.actionOpen.setObjectName("actionOpen")
        self.actionServer = QtGui.QAction(Dialog)
        self.actionServer.setObjectName("actionServer")
        self.actionDir = QtGui.QAction(Dialog)
        self.actionDir.setObjectName("actionDir")
        self.actionNuke = QtGui.QAction(Dialog)
        self.actionNuke.setObjectName("actionNuke")
        self.actionUpdateUI = QtGui.QAction(Dialog)
        self.actionUpdateUI.setObjectName("actionUpdateUI")
        self.actionOpenDir = QtGui.QAction(Dialog)
        self.actionOpenDir.setObjectName("actionOpenDir")
        self.actionOpenServer = QtGui.QAction(Dialog)
        self.actionOpenServer.setObjectName("actionOpenServer")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.dirButton, QtCore.SIGNAL("clicked()"), self.actionDir.trigger)
        QtCore.QObject.connect(self.nukeButton, QtCore.SIGNAL("clicked()"), self.actionNuke.trigger)
        QtCore.QObject.connect(self.openButton, QtCore.SIGNAL("clicked()"), self.actionOpen.trigger)
        QtCore.QObject.connect(self.serverButton, QtCore.SIGNAL("clicked()"), self.actionServer.trigger)
        QtCore.QObject.connect(self.syncButton, QtCore.SIGNAL("clicked()"), self.actionSync.trigger)
        QtCore.QObject.connect(self.sheetButton, QtCore.SIGNAL("clicked()"), self.actionSheet.trigger)
        QtCore.QObject.connect(self.toolButtonOpenDir, QtCore.SIGNAL("clicked()"), self.actionOpenDir.trigger)
        QtCore.QObject.connect(self.toolButtonOpenServer, QtCore.SIGNAL("clicked()"), self.actionOpenServer.trigger)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "场集工具", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "工作目录", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonOpenDir.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.dirButton.setText(QtGui.QApplication.translate("Dialog", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "工程名", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "集", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "场", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "视频文件夹名称", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "单帧文件夹名称", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "视频上传至", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "单帧上传至", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "上传", None, QtGui.QApplication.UnicodeUTF8))
        self.videoUpCheck.setText(QtGui.QApplication.translate("Dialog", "视频", None, QtGui.QApplication.UnicodeUTF8))
        self.imageUpCheck.setText(QtGui.QApplication.translate("Dialog", "单帧", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "下载", None, QtGui.QApplication.UnicodeUTF8))
        self.videoDownCheck.setText(QtGui.QApplication.translate("Dialog", "视频", None, QtGui.QApplication.UnicodeUTF8))
        self.imageDownCheck.setText(QtGui.QApplication.translate("Dialog", "单帧", None, QtGui.QApplication.UnicodeUTF8))
        self.syncButton.setText(QtGui.QApplication.translate("Dialog", "上传及下载", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage2), QtGui.QApplication.translate("Dialog", "上传下载", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "色板素材文件夹", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "色板名称前缀", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "色板底板", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "色板名称", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "色板上传至", None, QtGui.QApplication.UnicodeUTF8))
        self.csheetOpenCheck.setText(QtGui.QApplication.translate("Dialog", "创建后打开色板", None, QtGui.QApplication.UnicodeUTF8))
        self.csheetUpCheck.setText(QtGui.QApplication.translate("Dialog", "创建后上传色板", None, QtGui.QApplication.UnicodeUTF8))
        self.sheetButton.setText(QtGui.QApplication.translate("Dialog", "创建色板", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setText(QtGui.QApplication.translate("Dialog", "打开色板", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage1), QtGui.QApplication.translate("Dialog", "拼色板", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "工具", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "服务器路径", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonOpenServer.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.serverButton.setText(QtGui.QApplication.translate("Dialog", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "服务器视频路径", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "服务器单帧文件夹", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Nuke路径", None, QtGui.QApplication.UnicodeUTF8))
        self.nukeButton.setText(QtGui.QApplication.translate("Dialog", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "高级设置", None, QtGui.QApplication.UnicodeUTF8))
        self.version_label.setText(QtGui.QApplication.translate("Dialog", "version", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSheet.setText(QtGui.QApplication.translate("Dialog", "sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSync.setText(QtGui.QApplication.translate("Dialog", "sync", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("Dialog", "open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionServer.setText(QtGui.QApplication.translate("Dialog", "server", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDir.setText(QtGui.QApplication.translate("Dialog", "dir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuke.setText(QtGui.QApplication.translate("Dialog", "nuke", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateUI.setText(QtGui.QApplication.translate("Dialog", "updateUI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenDir.setText(QtGui.QApplication.translate("Dialog", "openDir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenServer.setText(QtGui.QApplication.translate("Dialog", "openServer", None, QtGui.QApplication.UnicodeUTF8))

