"""
This type stub file was generated by pyright.
"""

"""Functions used by the ApplyMaterial node"""

class ObjectNameChooserDialog(nukescripts.panels.PythonPanel):
    """A dialog box with a SceneView_Knob for choosing from a tree of names.

    The easiest way to use this is via the chooseObjectName function from this
    module, e.g.:

      chooseObjectName(["/root/foo", "/root/bar", "/root/bar/baz"])

    This will create and display the dialog as a modal popup and give you the
    selected name, or None if cancel was pressed.
    """

    def __init__(self, names) -> None: ...
    def selectedName(self):
        """Get the name selected in the SceneView_Knob."""
        ...

def chooseObjectName(amfNode):
    """Given an ApplyMaterial node, show a modal ObjectNameChooserDialog
    for it then set the filter_name knob to whatever name was selected in the
    dialog.
    """
    ...
