"""
This type stub file was generated by pyright.
"""

def nodeIsInside(node, backdropNode):
    """Returns true if node geometry is inside backdropNode otherwise returns false"""
    ...

def autoBackdrop():
    """
    Automatically puts a backdrop behind the selected nodes.

    The backdrop will be just big enough to fit all the select nodes in, with room
    at the top for some text in a large font.
    """
    ...
