"""
This type stub file was generated by pyright.
"""

def camera_up():
  """All new camera_up that uses the version_get/set functions.
  This script takes the render camera up one in selected iread/writes.
  Camera may be _c# or _p# for previs camera number"""
  ...

def camera_down():
  """All new camera_down that uses the version_get/set functions.
  This script takes the render camera up one in selected iread/writes.
  Camera may be _c# or _p# for previs camera number"""
  ...

def create_camera_here():
  ...

