"""
This type stub file was generated by pyright.
"""

HOST = "localhost"
PORT = 50007

class client:
    """
    Example of running an IPV6 socket client to create nodes in Nuke.

    from nukescripts import clientserver
    c = clientserver.client()
    c.send("Blur")
    """

    def __init__(self, host=..., port=...) -> None: ...
    def send(self, msg): ...
    def close(self): ...

class server:
    """
    Example of running an IPV6 socket server on a separate thread inside Nuke.
    The default command is to create the named node.

    from nukescripts import clientserver
    clientserver.threaded_server()
    """

    def __init__(self, host=..., port=...) -> None: ...
    def start(self): ...

def start_server(host=..., port=...): ...
def threaded_server(): ...
