"""
This type stub file was generated by pyright.
"""

from typing import Callable, Literal, Optional
from wulifang._compat.str import Str

TYPE_CHECKING = False
if TYPE_CHECKING:
    DropDataCallback = Callable[[Str, Str], Optional[Literal[True]]]

_gDropDataCallbacks: list[DropDataCallback] = []

def addDropDataCallback(callback: DropDataCallback) -> None:
    """Add a function to the list of callbacks. This function will called whenever data is dropped onto the DAG. Override it to perform other actions.
    If you handle the drop, return True, otherwise return None."""
    ...

def dropData(mimeType, text):
    """Handle data drops by invoking the list of callback functions until one has
    handled the event"""
    ...
