"""
This type stub file was generated by pyright.
"""

from typing import Callable, Literal, Optional

_gDropDataCallbacks = []

def addDropDataCallback(callback: Callable[..., Optional[Literal[True]]]) -> None:
    """Add a function to the list of callbacks. This function will called whenever data is dropped onto the DAG. Override it to perform other actions.
    If you handle the drop, return True, otherwise return None."""
    ...

def dropData(mimeType, text):
    """Handle data drops by invoking the list of callback functions until one has
    handled the event"""
    ...
