"""
This type stub file was generated by pyright.
"""

def cut_paste_file():
   ...

def node_copypaste():
   ...

def remove_inputs():
   ...

def extract():
   """Disconnect all arrows between selected and unselected nodes, and move selected nodes to the right.
  This function is maintained only for compatibility.  Please use nuke.extractSelected() instead."""
   ...

def branch():
   ...

