"""
This type stub file was generated by pyright.
"""

def toggle(knob):
    """ "Inverts" some flags on the selected nodes.

    What this really does is set all of them to the same value, by finding the
    majority value and using the inverse of that."""
    ...
