"""
This type stub file was generated by pyright.
"""

def goto_frame():
   ...

def replaceHashes(filename):
   '''replaceHashes(filename) -> string
  Replace any sequences of 1 or more hash marks (#) with a printf-style %0nd specifier.'''
   ...

