"""
This type stub file was generated by pyright.
"""

import nukescripts

class FrameRangePanel(nukescripts.PythonPanel):
    """class that creates a Python panel for editing frame ranges"""

    def __init__(self, initalStart, initialEnd) -> None:
        """Constructor that takes 2 arguments for the initial start and end frame numbers"""
        ...
    def showDialog(self):
        """show panel dialog, returns if accept was pressed"""
        ...
