"""
This type stub file was generated by pyright.
"""

import nuke

"""Functions used by the ModelBuilder node"""
def populateBakeMenu(mb):
  """Populate the bake menu on a ModelBuilder node."""
  ...

def bakeSceneSelection(mb):
  """Create a ModelBuilderGeo node containing a copy of the currently selected geometry."""
  ...

def bakeProjection(mb):
  """Create a projection setup for the current frame."""
  ...

def bakeApplyTexture(mb):
  ...

def clearNodeSelection():
  ...

def copyCamera(srcCam):
  ...

def modelbuilderCreateCallback():
  ...

assist = nuke.env['assist']
if not assist:
  ...
