"""
This type stub file was generated by pyright.
"""

import nuke
from nukescripts import pyAppUtils

class pyQtAppHelper(pyAppUtils.pyAppHelper, nuke.FnPySingleton):
  """ Helper class to initialise PyQt in a separate thread """
  def __init__(self, argv=..., start=...) -> None:
    ...
  
  def getApplication(self, argv):
    ...
  
  def closeApplication(self):
    ...
  
  def start(self, argv):
    ...
  
  def stop(self):
    ...
  


