"""
This type stub file was generated by pyright.
"""

from nukescripts import pyAppUtils

class pyWxAppHelper(pyAppUtils.pyAppHelper):
  """ Helper class to initialise wxWidgets in a separate thread """
  def __init__(self, wxApp, start=...) -> None:
    ...
  
  def getApplication(self):
    ...
  
  def start(self):
    ...
  


