"""
This type stub file was generated by pyright.
"""

def get_reads(method):
    """Returns file names from all Read nodes.

    Options:
      file - outputs only file names
      dir  - outputs only directory names
      long - outputs the entire path"""
    ...
