"""
This type stub file was generated by pyright.
"""

def select_by_name():
    """Menu command to select nodes by a glob-pattern name.
    This function is only maintained for backwards compatibility.
    Please use nuke.selectPattern() instead."""
    ...

def select_similar(_type):
    "Included only for compatibility.  Use nuke.selectSimilar()."
    ...
