"""
This type stub file was generated by pyright.
"""

__NODES_FOR_VERSION = ("Read", "Write", "Precomp", "DeepRead", "DeepWrite")
def version_get(string, prefix, suffix=...):
  """Extract version information from filenames used by DD (and Weta, apparently)
  These are _v# or /v# or .v# where v is a prefix string, in our case
  we use "v" for render version and "c" for camera track version.
  See the version.py and camera.py plugins for usage."""
  ...

def version_set(string, prefix, oldintval, newintval):
  """Changes version information from filenames used by DD (and Weta, apparently)
  These are _v# or /v# or .v# where v is a prefix string, in our case
  we use "v" for render version and "c" for camera track version.
  See the version.py and camera.py plugins for usage."""
  ...

def version_up():
  """All new version_up that uses the version_get/set functions.
  This script takes the render version up one in selected iread/writes."""
  ...

def version_down():
  """All new version_down that uses the version_get/set functions.
  This script takes the render version up one in selected iread/writes."""
  ...

def version_latest():
  """Like version_up, but only goes up to the highest numbered version
  that exists.

  Works on all selected Read nodes, or all Read nodes if nothing is
  selected.

  Does not modify Write nodes."""
  class __KnobValueReplacer(object):
    ...
  
  

