from typing import Generic, TypeVar, Callable

T = TypeVar("T")

class JSONStorageItem(Generic[T]):
    def __init__(self, _key: str, _default: Callable[[], T], /): ...
    def get(self) -> T: ...
    def set(self, value: T) -> None: ...
    def invalidate_cache(self) -> None: ...
