from typing import Generic, TypeVar, Callable

T = TypeVar("T")

class lazy_getter(Generic[T]):
    def __init__(self, load: Callable[[], T], /) -> None: ...
    def reset(self) -> None: ...
    def __call__(self) -> T: ...
