# -*- coding=UTF-8 -*-
# Code generated by scripts\python-version-updater.js, DO NOT EDIT
"""
version info.
"""

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from datetime import datetime

VERSION = '2021.4.1'
RELEASE_DATE = datetime.fromtimestamp(1636692377)
LAST_GIT_COMMIT_DESCRIBE = 'v2021.4.0-2-gb3ee633'
LAST_GIT_COMMIT_HASH = 'b3ee63311bf1fca32fff0abbba484c5be94a0916'
LAST_GIT_COMMIT_AUTHOR_NAME = 'NateScarlet'
LAST_GIT_COMMIT_AUTHOR_EMAIL = 'NateScarlet@Gmail.com'
LAST_GIT_COMMIT_AUTHOR_DATE = datetime.fromtimestamp(1636692358)
LAST_GIT_COMMIT_SUBJECT = 'fix(cgteamwork): error when workfile already uploaded'
LAST_GIT_COMMIT_BODY = ''
