# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uploader.ui'
#
# Created: Mon Aug 28 18:27:31 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(496, 535)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.toolButtonOpenDir = QtGui.QToolButton(Dialog)
        self.toolButtonOpenDir.setAutoRaise(True)
        self.toolButtonOpenDir.setObjectName("toolButtonOpenDir")
        self.horizontalLayout_5.addWidget(self.toolButtonOpenDir)
        self.dirEdit = QtGui.QLineEdit(Dialog)
        self.dirEdit.setDragEnabled(True)
        self.dirEdit.setObjectName("dirEdit")
        self.horizontalLayout_5.addWidget(self.dirEdit)
        self.dirButton = QtGui.QToolButton(Dialog)
        self.dirButton.setAutoRaise(True)
        self.dirButton.setObjectName("dirButton")
        self.horizontalLayout_5.addWidget(self.dirButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtGui.QListWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.frame = QtGui.QFrame(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(220, 0))
        self.frame.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toolBox = QtGui.QToolBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 0))
        self.toolBox.setObjectName("toolBox")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 200, 313))
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.toolButtonOpenServer = QtGui.QToolButton(self.page)
        self.toolButtonOpenServer.setAutoRaise(True)
        self.toolButtonOpenServer.setObjectName("toolButtonOpenServer")
        self.horizontalLayout_3.addWidget(self.toolButtonOpenServer)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.serverEdit = QtGui.QLineEdit(self.page)
        self.serverEdit.setDragEnabled(True)
        self.serverEdit.setObjectName("serverEdit")
        self.horizontalLayout_4.addWidget(self.serverEdit)
        self.serverButton = QtGui.QToolButton(self.page)
        self.serverButton.setAutoRaise(True)
        self.serverButton.setObjectName("serverButton")
        self.horizontalLayout_4.addWidget(self.serverButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtGui.QLabel(self.page)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.projectEdit = QtGui.QLineEdit(self.page)
        self.projectEdit.setObjectName("projectEdit")
        self.horizontalLayout_12.addWidget(self.projectEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.epEdit = QtGui.QLineEdit(self.page)
        self.epEdit.setObjectName("epEdit")
        self.horizontalLayout.addWidget(self.epEdit)
        self.label = QtGui.QLabel(self.page)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.scEdit = QtGui.QLineEdit(self.page)
        self.scEdit.setObjectName("scEdit")
        self.horizontalLayout.addWidget(self.scEdit)
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.folderEdit = QtGui.QLineEdit(self.page)
        self.folderEdit.setObjectName("folderEdit")
        self.verticalLayout_2.addWidget(self.folderEdit)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtGui.QWidget()
        self.page_2.setEnabled(False)
        self.page_2.setGeometry(QtCore.QRect(0, 0, 200, 313))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout_5.addWidget(self.toolBox)
        self.syncButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syncButton.sizePolicy().hasHeightForWidth())
        self.syncButton.setSizePolicy(sizePolicy)
        self.syncButton.setMinimumSize(QtCore.QSize(0, 50))
        self.syncButton.setObjectName("syncButton")
        self.verticalLayout_5.addWidget(self.syncButton)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.destEdit = QtGui.QLineEdit(Dialog)
        self.destEdit.setFrame(False)
        self.destEdit.setReadOnly(True)
        self.destEdit.setObjectName("destEdit")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.destEdit)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.version_label = QtGui.QLabel(Dialog)
        self.version_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_label.setObjectName("version_label")
        self.verticalLayout.addWidget(self.version_label)
        self.actionSheet = QtGui.QAction(Dialog)
        self.actionSheet.setObjectName("actionSheet")
        self.actionSync = QtGui.QAction(Dialog)
        self.actionSync.setObjectName("actionSync")
        self.actionOpen = QtGui.QAction(Dialog)
        self.actionOpen.setObjectName("actionOpen")
        self.actionServer = QtGui.QAction(Dialog)
        self.actionServer.setObjectName("actionServer")
        self.actionDir = QtGui.QAction(Dialog)
        self.actionDir.setObjectName("actionDir")
        self.actionNuke = QtGui.QAction(Dialog)
        self.actionNuke.setObjectName("actionNuke")
        self.actionUpdateUI = QtGui.QAction(Dialog)
        self.actionUpdateUI.setObjectName("actionUpdateUI")
        self.actionOpenDir = QtGui.QAction(Dialog)
        self.actionOpenDir.setObjectName("actionOpenDir")
        self.actionOpenServer = QtGui.QAction(Dialog)
        self.actionOpenServer.setObjectName("actionOpenServer")

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.dirButton, QtCore.SIGNAL("clicked()"), self.actionDir.trigger)
        QtCore.QObject.connect(self.serverButton, QtCore.SIGNAL("clicked()"), self.actionServer.trigger)
        QtCore.QObject.connect(self.toolButtonOpenDir, QtCore.SIGNAL("clicked()"), self.actionOpenDir.trigger)
        QtCore.QObject.connect(self.toolButtonOpenServer, QtCore.SIGNAL("clicked()"), self.actionOpenServer.trigger)
        QtCore.QObject.connect(self.syncButton, QtCore.SIGNAL("clicked()"), self.actionSync.trigger)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "上传工具", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "输入目录", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonOpenDir.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.dirButton.setText(QtGui.QApplication.translate("Dialog", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "服务器", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonOpenServer.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.serverButton.setText(QtGui.QApplication.translate("Dialog", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "工程", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "集", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "场", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "文件夹", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("Dialog", "至服务器文件夹", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("Dialog", "至CGTeamWork(当前不可用)", None, QtGui.QApplication.UnicodeUTF8))
        self.syncButton.setText(QtGui.QApplication.translate("Dialog", "上传", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "上传至", None, QtGui.QApplication.UnicodeUTF8))
        self.version_label.setText(QtGui.QApplication.translate("Dialog", "version", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSheet.setText(QtGui.QApplication.translate("Dialog", "sheet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSync.setText(QtGui.QApplication.translate("Dialog", "sync", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("Dialog", "open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionServer.setText(QtGui.QApplication.translate("Dialog", "server", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDir.setText(QtGui.QApplication.translate("Dialog", "dir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuke.setText(QtGui.QApplication.translate("Dialog", "nuke", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateUI.setText(QtGui.QApplication.translate("Dialog", "updateUI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenDir.setText(QtGui.QApplication.translate("Dialog", "openDir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenServer.setText(QtGui.QApplication.translate("Dialog", "openServer", None, QtGui.QApplication.UnicodeUTF8))

