"""
This type stub file was generated by pyright.
"""

from typing import Callable, Any, Any, TypeVar

T = TypeVar("T")

def executeInMainThreadWithResult(
    call: Callable[..., T], args: Any = ..., kwargs: Any = ...
) -> T:
    """Execute the callable 'call' with optional arguments 'args' and named arguments 'kwargs' in
    Nuke's main thread and wait for the result to become available."""
    ...

def executeInMainThread(call, args=..., kwargs=...):
    """Execute the callable 'call' with optional arguments 'args' and named
    arguments 'kwargs' i n Nuke's main thread and return immediately."""
    ...
