"""
This type stub file was generated by pyright.
"""

from curveknob import *

"""The Python interface for used by SplineWarp

Use help('_splinewarp') to get detailed help on the classes exposed here.
"""
