# -*- coding=UTF-8 -*-
# This typing file was generated by typing_from_help.py
"""
pyblish - Pyblish initialisation
"""

import six
import typing

"""
Attributes:
    _registered_paths: Currently registered plug-in paths.
    _registered_plugins: Currently registered plug-ins.
"""
__all__: ...
"""
['__all__', '__builtins__', '__doc__', '__file__', '__name__...
"""

__version__: six.binary_type
"""
'1.8.8'
"""

_registered_callbacks: dict
"""
{}
"""

_registered_gui: list
"""
[]
"""

_registered_hosts: list
"""
[]
"""

_registered_paths: list
"""
[]
"""

_registered_plugin_filters: list
"""
[]
"""

_registered_plugins: dict
"""
{}
"""

_registered_services: dict
"""
{}
"""

_registered_targets: list
"""
[]
"""

_registered_test: dict
"""
{}
"""

version: six.binary_type
"""
'1.8.8'
"""

version_info: ... = (1, 8, 8)

# version: 1.8.8
